spring:
  application:
    name: edge-courses
  liquibase:
    enabled: false

management.endpoints.web.base-path: /admin
header.validation.x-okapi-tenant.exclude.base-paths: /admin,/swagger,/v2/api-docs
server.error.include-message: always

logging:
  config: classpath:log4j2.xml

server:
  port: 8080

security:
  store: ${secure_store:Ephemeral}
  props-location: ${secure_store_props:src/main/resources/ephemeral.properties}

token:
  capacity: ${token_cache_capacity:100}
  ttl-ms: ${token_cache_ttl_ms:3600000}
  fail-ttl-ms: ${null_token_cache_ttl_ms:30000}