openapi: 3.0.0
info:
  title: Courses API
  version: v1

servers:
  - url: /courses/

paths:
  /courses/courses:
    get:
      operationId: getCoursesByQuery
      summary: Retrieve course reserves associated with the keyword query from folio mod-courses
      description: Retrieve course reserves associated with the keyword query
      parameters:
        - $ref: 'yml-utils/traits/common-components.yaml#/components/parameters/x-okapi-tenant-header'
        - $ref: 'yml-utils/traits/common-components.yaml#/components/parameters/x-okapi-token-header'
        - $ref: 'yml-utils/traits/common-components.yaml#/components/parameters/request-query-parameters'
      responses:
        '200':
          description: 'Calls the mod-courses GET /coursereserves/courses API and returns the result as-is
          The example of response: https://github.com/folio-org/mod-courses/blob/master/ramls/examples/reserves.json'
          content:
            application/json:
              schema:
                type: string
        '400':
          $ref: 'yml-utils/traits/common-components.yaml#/components/responses/badRequestResponse'
        '500':
          $ref: 'yml-utils/traits/common-components.yaml#/components/responses/internalServerErrorResponse'
  /courses/courselistings/{instanceId}/reserves:
    get:
      operationId: getCoursesByInstanceId
      summary: Retrieve course reserves associated with the course instance id from folio mod-courses
      description: Retrieve course reserves associated with course instance id
      parameters:
        - $ref: '#/components/parameters/instance-id-path'
        - $ref: 'yml-utils/traits/common-components.yaml#/components/parameters/x-okapi-tenant-header'
        - $ref: 'yml-utils/traits/common-components.yaml#/components/parameters/x-okapi-token-header'
        - $ref: 'yml-utils/traits/common-components.yaml#/components/parameters/request-query-parameters'
      responses:
        '200':
          description: 'Calls the mod-courses GET /coursereserves/courselistings/{listing_id}/courses API and returns the result as-is
          The example of response: https://github.com/folio-org/mod-courses/blob/master/ramls/examples/reserves.json'
          content:
            application/json:
              schema:
                type: string
        '400':
          $ref: 'yml-utils/traits/common-components.yaml#/components/responses/badRequestResponse'
        '500':
          $ref: 'yml-utils/traits/common-components.yaml#/components/responses/internalServerErrorResponse'

components:
  parameters:
    instance-id-path:
      name: instanceId
      in: path
      description: Course Instance's UUID
      required: true
      schema:
        type: string
